[colors.primary]
background = "#000000"
foreground = "#ffffff"
dim_foreground = "#808080"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#FF1A1A"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#FF1A1A"

[colors.search.matches]
foreground = "#000000"
background = "#FF1A1A"

[colors.search.focused_match]
foreground = "#000000"
background = "#FF1A1A"

[colors.footer_bar]
foreground = "#000000"
background = "#FF1A1A"

[colors.hints.start]
foreground = "#000000"
background = "#FF1A1A"

[colors.hints.end]
foreground = "#000000"
background = "#FF1A1A"

[colors.selection]
text = "#000000"
background = "#FF1A1A"

[colors.normal]
black = "#000000"
red = "#FF1A1A"
green = "#FF1A1A"
yellow = "#FF1A1A"
blue = "#2A2A2A"
magenta = "#FF1A1A"
cyan = "#FF1A1A"
white = "#ffffff"

[colors.bright]
black = "#2A2A2A"
red = "#FF1A1A"
green = "#FF1A1A"
yellow = "#FF1A1A"
blue = "#2A2A2A"
magenta = "#FF1A1A"
cyan = "#FF1A1A"
white = "#ffffff"

[colors.dim]
black = "#000000"
red = "#FF1A1A"
green = "#FF1A1A"
yellow = "#FF1A1A"
blue = "#2A2A2A"
magenta = "#FF1A1A"
cyan = "#FF1A1A"
white = "#808080"

[[colors.indexed_colors]]
index = 16
color = "#FF1A1A"

[[colors.indexed_colors]]
index = 17
color = "#FF1A1A"

