[colors.primary]
background = "#000000"
foreground = "#ffffff"
dim_foreground = "#808080"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#dc2626"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#dc2626"

[colors.search.matches]
foreground = "#000000"
background = "#dc2626"

[colors.search.focused_match]
foreground = "#000000"
background = "#dc2626"

[colors.footer_bar]
foreground = "#000000"
background = "#dc2626"

[colors.hints.start]
foreground = "#000000"
background = "#dc2626"

[colors.hints.end]
foreground = "#000000"
background = "#dc2626"

[colors.selection]
text = "#000000"
background = "#dc2626"

[colors.normal]
black = "#000000"
red = "#dc2626"
green = "#16a34a"
yellow = "#ca8a04"
blue = "#2563eb"
magenta = "#9333ea"
cyan = "#0891b2"
white = "#ffffff"

[colors.bright]
black = "#404040"
red = "#dc2626"
green = "#16a34a"
yellow = "#ca8a04"
blue = "#2563eb"
magenta = "#9333ea"
cyan = "#0891b2"
white = "#ffffff"

[colors.dim]
black = "#000000"
red = "#dc2626"
green = "#16a34a"
yellow = "#ca8a04"
blue = "#2563eb"
magenta = "#9333ea"
cyan = "#0891b2"
white = "#808080"

[[colors.indexed_colors]]
index = 16
color = "#dc2626"

[[colors.indexed_colors]]
index = 17
color = "#dc2626"

