return {
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "tokyonight",
		},
	},
	{
		"folke/tokyonight.nvim",
		opts = {
			style = "night",
			transparent = false,
			terminal_colors = true,
			styles = {
				comments = { italic = true },
				keywords = { italic = true },
				functions = {},
				variables = {},
			},
			sidebars = { "qf", "help" },
			day_brightness = 0.3,
			hide_inactive_statusline = false,
			dim_inactive = true,
			lualine_bold = false,
			colors = {
				-- Override with TRON ARES colors
				red = "#FF1A1A",
				orange = "#FF1A1A",
				yellow = "#FF1A1A",
				green = "#FF1A1A",
				cyan = "#FF1A1A",
				blue = "#2A2A2A",
				magenta = "#FF1A1A",
				pink = "#FF1A1A",
				comment = "#808080",
				bg = "#000000",
				bg_dark = "#000000",
				bg_float = "#000000",
				bg_highlight = "#2A2A2A",
				bg_popup = "#000000",
				bg_search = "#FF1A1A",
				bg_sidebar = "#000000",
				bg_statusline = "#000000",
				bg_visual = "#2A2A2A",
				border = "#2A2A2A",
				fg = "#ffffff",
				fg_dark = "#808080",
				fg_float = "#ffffff",
				fg_gutter = "#404040",
				fg_sidebar = "#ffffff",
				git = {
					add = "#FF1A1A",
					change = "#FF1A1A",
					delete = "#FF1A1A",
					ignore = "#404040",
				},
				gitSigns = {
					add = "#FF1A1A",
					change = "#FF1A1A",
					delete = "#FF1A1A",
				},
			},
		},
	},
}
